# Add 'frontend' label to any change within 'src/components' folder
frontend:
  - changed-files:
    - any-glob-to-any-file: 'src/components/**'
    - any-glob-to-any-file: 'src/app/**'
    - any-glob-to-any-file: '*.css'
    - any-glob-to-any-file: '*.scss'

# Add 'backend' label to any change within 'src/api' or 'src/lib' folders
backend:
  - changed-files:
    - any-glob-to-any-file: 'src/api/**'
    - any-glob-to-any-file: 'src/lib/**'
    - any-glob-to-any-file: 'src/ai/**'

# Add 'workflows' label when workflow files change
workflows:
  - changed-files:
    - any-glob-to-any-file: 'src/workflows/**'

# Add 'tests' label when test files change
tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'
    - any-glob-to-any-file: '**/*.test.ts'
    - any-glob-to-any-file: '**/*.spec.ts'

# Add 'documentation' label when markdown files change
documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
    - any-glob-to-any-file: 'docs/**'

# Add 'dependencies' label when package files change
dependencies:
  - changed-files:
    - any-glob-to-any-file: 'package.json'
    - any-glob-to-any-file: 'package-lock.json'
    - any-glob-to-any-file: 'yarn.lock'

# Add 'config' label when configuration files change
config:
  - changed-files:
    - any-glob-to-any-file: '*.config.*'
    - any-glob-to-any-file: '.github/**'
    - any-glob-to-any-file: 'firebase.json'
    - any-glob-to-any-file: 'apphosting.yaml'