name: PR Automation

on:
  pull_request:
    types: [opened, edited, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  auto-label:
    name: Auto Label PRs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        
  size-label:
    name: Add Size Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/xs'
        xs_max_size: '10'
        s_label: 'size/s'
        s_max_size: '100'
        m_label: 'size/m'
        m_max_size: '500'
        l_label: 'size/l'
        l_max_size: '1000'
        xl_label: 'size/xl'
        
  auto-assign:
    name: Auto Assign Reviewers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        configuration-path: .github/auto-assign.yml